[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "meridian"
version = "0.0.2"
dependencies = [
    "numpy<2",
    "alphashape",
    "trimesh",
    "manifold3d",
    "rasterio<1.5",
    "circle-fit",
    "segment-anything",
    "einops",
    "fast-pytorch-kmeans",
    "open3d",
    "transformers",
    "numba",
    "yolov7-package",
    "robotdatapy",
    "gdown",
    "vpr @ git+ssh://git@gitlab.com/mit-acl/sparse_mapping/vpr.git"
    # for dinov3
    #"torchmetrics",
    #"termcolor",
    #"segment_anything @ git+https://github.com/facebookresearch/segment-anything.git"
]
requires-python = ">=3.8"
authors = [
    {name = "Mason Peterson", email = "mbpeterson70@gmail.com"},
    {name = "Andy Li", email = "andyli27@mit.edu"}
]
description = "Package for localizing a ground robot from aerial ortho-imagery, providing meter-level pose estimates without any initial pose information or environmental fine-tuning."
readme = "README.md"
license = "MIT"


